version: "3.8"
services:
  app:
    build: .
    image: secure_note
    container_name: secure_note
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
